from analysis.selections.utils import delta_r_mask, select_dileptons, select_zzto4l_zz_candidates
from analysis.selections.object_selections import ObjectSelector
import analysis.selections.event_selections as event_selections
get_lumi_mask = event_selections.get_lumi_mask
get_trigger_mask = event_selections.get_trigger_mask